version: '1.0.{build}'
image: Visual Studio 2017
environment:
  currentBranch: "https://github.com/VladislavSudakov/netcore-facebook-login.git"
  op_build_user: "VladislavSudakov"
  op_build_user_email:
    secure: zEIkuPkUH8R7UIddM//zZsDFNUI5cd3+rHRNVZoaZjw=
  access_token:
    secure: JZO2ktMxPXknVv5WsAwlHgOVtZdzn06ObTxhRhvpWyKDdmUDzs8kq8jf3kls1edj
branches:
  only:
  - master
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
install:
  - cinst docfx
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore SimpleSoft.AspNetCore.FacebookGraphApi.sln --verbosity m
build_script:
  - cmd: dotnet publish SimpleSoft.AspNetCore.FacebookGraphApi.sln
after_build:
  - cmd: dotnet pack src/SimpleSoft.AspNetCore.FacebookGraphApi.csproj /p:Version=%APPVEYOR_BUILD_VERSION%
  - ps: |
          docfx docs/docfx.json
          if ($lastexitcode -ne 0){
            throw [System.Exception] "docfx build failed with exit code $lastexitcode."
          }
            
          git config --global credential.helper store
          Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
          git config --global user.email $env:op_build_user_email
          git config --global user.name $env:op_build_user
          git clone $env:currentBranch -b gh-pages origin_site -q

          Copy-Item origin_site/.git docs/_site -recurse
          CD docs/_site
          git add -A 2>&1
          git commit -m "CI Updates" -q
          git push origin gh-pages -q
artifacts:
 - path: '**\*.nupkg'
   name: NetCore-Facebook-Login
   type: NuGetPackage
clone_depth: 1
test_script:
  - cmd: dotnet test tests/SimpleSoft.AspNetCore.FacebookGraphApi.Tests/SimpleSoft.AspNetCore.FacebookGraphApi.Tests.csproj
on_finish :
  # any cleanup in here
deploy:
  provider: NuGet
  api_key:
    secure: XcHzKbqYxZO9NFL20Q4/Dvp8RSyZd5rJ5Fvimg7ZhR7ZWOwGV63gdr6s9p8NpFUj
  skip_symbols: false
  artifact: /.*\.nupkg/