version: '1.0.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
install:
  # Install repo specific stuff here
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore SimpleSoft.AspNetCore.FacebookGraphApi.sln --verbosity m
build_script:
  - cmd: dotnet publish SimpleSoft.AspNetCore.FacebookGraphApi.sln
after_build:
  - cmd: dotnet pack SimpleSoft.AspNetCore.FacebookGraphApi.csproj /p:Version=%APPVEYOR_BUILD_VERSION%
artifacts:
 - path: '**\*.nupkg'
   name: NetCore-Facebook-Login
   type: NuGetPackage
clone_depth: 1
test_script:
  # restore packages for our unit tests
  # - cmd: dotnet restore ./tests/tests.csproj --verbosity m
  # run the unit tests (requires changing into the test directory)
  # - cmd: cd tests
  # - cmd: dotnet xunit
on_finish :
  # any cleanup in here
deploy:
  provider: NuGet
  api_key:
    secure: XcHzKbqYxZO9NFL20Q4/Dvp8RSyZd5rJ5Fvimg7ZhR7ZWOwGV63gdr6s9p8NpFUj
  skip_symbols: false
  artifact: /.*\.nupkg/